const x = 10

try{
    if(x === 10){
        console.log("Passou no teste!")
    }
} catch(err){
    console.log(`Erro: ${err}`)
}